machineClasses:
- name: class-1
  region: myregion
  datacenter: dc1
  #hostSystem: esxi1
  #resourcePool: pool1
  computeCluster: cluster1
  network: network1
  #switchUuid: "11 22-33 44"
  folder: gardener
  datastore: datastore1
  #datastoreCluster: ds-cluster
  templateVM: "gardener/templates/coreos-2191.5.0"
  guestId: coreos64Guest
  numCpus: 2
  memory: 4096
  #memoryReservationLockedToMax: true
  #extraConfig:
  #  sched.swap.vmxSwapEnabled: "false"
  systemDisk:
    size: 20
  description: An optional description for machines created by that class.
  machineType: t1.small
  sshKeys:
  - 12345-abcd567-aaf2
  secret:
    cloudConfig: abc
    vsphereHost: "a_host"
    vsphereUsername: "a_user"
    vspherePassword: "a_password"
    vsphereInsecureSSL: "true"
    # value for vsphereWithKubernetes == true
    vsphereKubeconfig: ZHVtbXk=
  tags:
  - kubernetes.io/cluster/foo
  - kubernetes.io/role/node

  # values for vsphereWithKubernetes == true
  namespace: "shoot--foo--bar"
  imageName: "gardenlinux-123.0"
  className: "best-effort-medium"
  networkType: "nsx-t"
  networkName: "shoot--foo--bar"

vsphereWithKubernetes: false
