{{- range $index, $machineClass := .Values.machineClasses }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    gardener.cloud/purpose: machineclass
type: Opaque
data:
  userData: {{ $machineClass.secret.cloudConfig | b64enc }}
{{- if $.Values.vsphereWithKubernetes }}
  vsphereKubeconfig: {{ $machineClass.secret.vsphereKubeconfig | b64enc }}
{{- else }}
  vsphereHost: {{ $machineClass.secret.vsphereHost | b64enc }}
  vsphereUsername: {{ $machineClass.secret.vsphereUsername | b64enc }}
  vspherePassword: {{ $machineClass.secret.vspherePassword | b64enc }}
  vsphereInsecureSSL: {{ $machineClass.secret.vsphereInsecureSSL | b64enc }}
{{- end }}
---
apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
providerSpec:
{{- if not $.Values.vsphereWithKubernetes }}
  V1:
    region: {{ $machineClass.region }}
    datacenter: {{ $machineClass.datacenter }}
{{- if $machineClass.hostSystem }}
    hostSystem: {{ $machineClass.hostSystem }}
{{- else }}
{{- if $machineClass.resourcePool }}
    resourcePool: {{ $machineClass.resourcePool }}
{{- else }}
    computeCluster: {{ $machineClass.computeCluster }}
{{- end }}
{{- end }}
    network: {{ $machineClass.network }}
{{- if $machineClass.switchUuid }}
    switchUuid: {{ $machineClass.switchUuid }}
{{- end }}
{{- if $machineClass.folder }}
    folder: {{ $machineClass.folder }}
{{- end }}
{{- if $machineClass.datastoreCluster }}
    datastoreCluster: {{ $machineClass.datastoreCluster }}
{{- else }}
    datastore: {{ $machineClass.datastore }}
{{- end }}
    templateVM: {{ $machineClass.templateVM }}
{{- if $machineClass.guestId }}
    guestId: {{ $machineClass.guestId }}
{{- end }}
    numCpus: {{ $machineClass.numCpus }}
    memory: {{ $machineClass.memory }}
{{- if $machineClass.memoryReservationLockedToMax }}
    memoryReservationLockedToMax: {{ $machineClass.memoryReservationLockedToMax }}
{{- end }}
{{- if $machineClass.extraConfig }}
    extraConfig:
{{ toYaml $machineClass.extraConfig | indent 6 }}
{{- end }}
    systemDisk:
  {{ toYaml $machineClass.systemDisk | indent 4 }}
{{- else }}
  V2:
    namespace: {{ $machineClass.namespace }}
    imageName: {{ $machineClass.imageName }}
    className: {{ $machineClass.className }}
    networkType: {{ $machineClass.networkType }}
    networkName: {{ $machineClass.networkName }}
{{- if $machineClass.storageClass }}
    storageClass: {{ $machineClass.storageClass }}
{{- end}}
{{- if $machineClass.resourcePolicyName }}
    resourcePolicyName: {{ $machineClass.resourcePolicyName }}
{{- end}}
    systemDisk:
  {{ toYaml $machineClass.systemDisk | indent 4 }}
{{- end }}
  sshKeys:
{{ toYaml $machineClass.sshKeys | indent 4 }}
{{- if $machineClass.tags }}
  tags:
{{ toYaml $machineClass.tags | indent 4 }}
{{- end }}
secretRef:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
provider: vsphere
{{- end }}
