---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gardener:cloud-controller-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gardener:cloud-controller-manager
subjects:
  - kind: ServiceAccount
    name: cloud-controller-manager
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gardener:cloud-controller-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["vmoperator.vmware.com"]
    resources: ["virtualmachines"]
    verbs: ["get", "list"]
