images:
- name: csi-attacher
  sourceRepository: github.com/kubernetes-csi/external-attacher
  repository: registry.k8s.io/sig-storage/csi-attacher
  tag: v3.5.0
- name: csi-resizer
  sourceRepository: github.com/kubernetes-csi/external-resizer
  repository: registry.k8s.io/sig-storage/csi-resizer
  tag: v1.5.0
- name: csi-node-driver-registrar
  sourceRepository: github.com/kubernetes-csi/node-driver-registrar
  repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
  tag: v2.5.1
- name: csi-provisioner
  sourceRepository: github.com/kubernetes-csi/external-provisioner
  repository: registry.k8s.io/sig-storage/csi-provisioner
  tag: v3.2.1
  targetVersion: ">= 1.20"
- name: csi-snapshotter
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: registry.k8s.io/sig-storage/csi-snapshotter
  tag: v6.0.1
  targetVersion: ">= 1.20"
- name: csi-snapshot-controller
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: registry.k8s.io/sig-storage/snapshot-controller
  tag: v6.0.1
  targetVersion: ">= 1.20"
- name: csi-snapshot-validation-webhook
  sourceRepository: github.com/kubernetes-csi/external-snapshotter
  repository: registry.k8s.io/sig-storage/snapshot-validation-webhook
  tag: v6.0.1
  targetVersion: ">= 1.20"
- name: vsphere-cloud-controller-manager
  sourceRepository: github.com/kubernetes/cloud-provider-vsphere
  repository: gcr.io/cloud-provider-vsphere/cpi/release/manager
  tag: v1.24.2
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "v0.49.2"
- name: machine-controller-manager-provider-vsphere
  sourceRepository: github.com/gardener/machine-controller-manager-provider-vsphere
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager-provider-vsphere
  tag: "v0.19.0"
- name: vsphere-csi-driver-controller
  sourceRepository: github.com/gardener/vsphere-csi-driver
  repository: eu.gcr.io/gardener-project/patches/vsphere-csi-driver/driver
  tag: v2.6.0-gardener3
- name: vsphere-csi-driver-node
  sourceRepository: github.com/gardener/vsphere-csi-driver
  repository: eu.gcr.io/gardener-project/patches/vsphere-csi-driver/driver
  tag: v2.6.0-gardener3
- name: vsphere-csi-driver-syncer
  sourceRepository: github.com/gardener/vsphere-csi-driver
  repository: eu.gcr.io/gardener-project/patches/vsphere-csi-driver/syncer
  tag: v2.6.0-gardener3
- name: liveness-probe
  sourceRepository: github.com/kubernetes-csi/livenessprobe
  repository: registry.k8s.io/sig-storage/livenessprobe
  tag: v2.7.0
