---
# AWS Route53 as DNS provider
apiVersion: v1
kind: Secret
metadata:
  name: default-domain
  namespace: garden
  labels:
    garden.sapcloud.io/role: default-domain
    gardener.cloud/role: default-domain
  annotations:
    dns.gardener.cloud/provider: aws-route53
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID}}
  AWS_REGION: {{ .Values.AWS_REGION}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY}}
# Secret containing a Diffie Hellman key used for all Shoot clusters on the targeted Garden cluster.
---
# AWS Route53 as DNS provider
apiVersion: v1
kind: Secret
metadata:
  name: internal-domain
  namespace: garden
  labels:
    garden.sapcloud.io/role: internal-domain
    gardener.cloud/role: internal-domain
  annotations:
    dns.gardener.cloud/provider: aws-route53
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID}}
  AWS_REGION: {{ .Values.AWS_REGION}}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY}}
# Secret containing a Diffie Hellman key used for all Shoot clusters on the targetted Garden cluster.
---
apiVersion: v1
kind: Secret
metadata:
  name: openvpn-diffie-hellman-key
  namespace: garden
  labels:
    garden.sapcloud.io/role: openvpn-diffie-hellman
type: Opaque
data:
  dh2048.pem: {{ .Values.vpn_key }}