---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    resources.gardener.cloud/delete-on-invalid-update: "true"
provisioner: csi.vsphere.vmware.com
volumeBindingMode: {{ .Values.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.allowVolumeExpansion }}
parameters:
  {{ .Values.storagePolicyNameKey }}: "{{ .Values.storagePolicyName }}"
