apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vsphere-csi-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: vsphere-csi-controller
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: vsphere-csi-controller
